// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzHg6PA2O6ts-84JDUnmZR5QGIiHshj-A',
    appId: '1:584999283993:web:f7b801968d8ad5e840e988',
    messagingSenderId: '584999283993',
    projectId: 'finalsem-e118d',
    authDomain: 'finalsem-e118d.firebaseapp.com',
    storageBucket: 'finalsem-e118d.appspot.com',
    measurementId: 'G-1D0TLNWTRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANJqQsI01pgBlcROXvjhXRg40POdTspao',
    appId: '1:584999283993:android:17036545042794d940e988',
    messagingSenderId: '584999283993',
    projectId: 'finalsem-e118d',
    storageBucket: 'finalsem-e118d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz4oDZSMa87gO6nQYN6TJ_N7OjvmQT1nI',
    appId: '1:584999283993:ios:fb061b4dce0ca5a740e988',
    messagingSenderId: '584999283993',
    projectId: 'finalsem-e118d',
    storageBucket: 'finalsem-e118d.appspot.com',
    iosClientId: '584999283993-cbj28kn09fshlar5nb5d4ajng8ghp2ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.recuirmentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz4oDZSMa87gO6nQYN6TJ_N7OjvmQT1nI',
    appId: '1:584999283993:ios:fb061b4dce0ca5a740e988',
    messagingSenderId: '584999283993',
    projectId: 'finalsem-e118d',
    storageBucket: 'finalsem-e118d.appspot.com',
    iosClientId: '584999283993-cbj28kn09fshlar5nb5d4ajng8ghp2ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.recuirmentapp',
  );
}
